# Generated by Django 3.0.5 on 2020-05-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='inspire/photos'),
        ),
    ]
