# Generated by Django 3.0.5 on 2020-05-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
