# Generated by Django 3.0.5 on 2020-05-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200505_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name', 'brand']},
        ),
        migrations.AlterModelOptions(
            name='makeupartist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='photographer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stylist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supermodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='beautytip',
            table='beautytip',
        ),
        migrations.AlterModelTable(
            name='camera',
            table='camera',
        ),
        migrations.AlterModelTable(
            name='cloth',
            table='cloth',
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='makeupartist',
            table='make_up_artist',
        ),
        migrations.AlterModelTable(
            name='makeupwork',
            table='makeup',
        ),
        migrations.AlterModelTable(
            name='modelwork',
            table='model_work',
        ),
        migrations.AlterModelTable(
            name='photo',
            table='photo',
        ),
        migrations.AlterModelTable(
            name='photographer',
            table='photographer',
        ),
        migrations.AlterModelTable(
            name='photographerwork',
            table='photographer_work',
        ),
        migrations.AlterModelTable(
            name='portfolio',
            table='portfolio',
        ),
        migrations.AlterModelTable(
            name='stylist',
            table='stylist',
        ),
        migrations.AlterModelTable(
            name='stylistwork',
            table='stylist_work',
        ),
        migrations.AlterModelTable(
            name='supermodel',
            table='supermodel',
        ),
    ]
