# Generated by Django 3.0.5 on 2020-05-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200505_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='makeupartist',
            options={'verbose_name': 'make_up_artist'},
        ),
        migrations.AlterModelOptions(
            name='photographer',
            options={'verbose_name': 'photographer'},
        ),
        migrations.AlterModelOptions(
            name='stylist',
            options={'verbose_name': 'stylist'},
        ),
        migrations.AlterModelOptions(
            name='supermodel',
            options={'verbose_name': 'supermodel'},
        ),
        migrations.AddField(
            model_name='user',
            name='blog_url',
            field=models.URLField(blank=True, null=True, verbose_name='blog url'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='inspire/photos/profiles'),
        ),
    ]
