# Generated by Django 3.0.5 on 2020-05-06 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user', '0006_auto_20200505_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('title', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='photographer',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='supermodel',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='makeupwork',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelwork',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='make_up_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeupartist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photographer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stylist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='super_models',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photographerwork',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stylistwork',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MakeUpArtist',
        ),
        migrations.DeleteModel(
            name='Photographer',
        ),
        migrations.DeleteModel(
            name='Stylist',
        ),
        migrations.DeleteModel(
            name='SuperModel',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='user.Role'),
        ),
    ]
